spring:
  application:
    name: "gatewayserver"
  config:
    import: "optional:configserver:http://localhost:8071/"
  cloud:
    gateway:
      discovery:
        locator:
          enabled: false
          lowerCaseServiceId: true
########## Circuit Breaker Global time out settings for all apis Start ############
      httpclient:
        connect-timeout: 3000
        response-timeout: 30s

  data:
    redis:
      connect-timeout: 2s
      host: localhost
      port: 6379
      timeout: 1s
########## Circuit Breaker End ############

########## Keyclock server Start ############
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: "http://localhost:7080/realms/master/protocol/openid-connect/certs"
########## Keyclock server End ############

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    gateway:
      enabled: true
  info:
    env:
      enabled: true
#### Metrics related config for prometheus to capture data start ######
  metrics:
    tags:
      application: ${spring.application.name}
#### Metrics related config for prometheus to capture data end ######

info:
  app:
    name: "gatewayserver"
    description: "Eazy Bank Gateway Server Application"
    version: "1.0.0"

logging:
  level:
    com:
      sarthak:
        gatewayserver: DEBUG
########## Open telemetry Start #######################
  pattern:
    level: "%5p [${spring.application.name},%X{trace_id},%X{span_id}]"
########## Open telemetry End #######################

########## Circuit Breaker Start ############
resilience4j.circuitbreaker:
  configs:
    default:
      slidingWindowSize: 10
      permittedNumberOfCallsInHalfOpenState: 2
      failureRateThreshold: 50
      waitDurationInOpenState: 10000
########## Circuit Breaker End ############