
spring:
  application:
    name: "eurekaserver"
  config:
    import: "optional:configserver:http://localhost:8071/"

management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true
  endpoint:
    health:
      probes:
        enabled: true
#### Metrics related config for prometheus to capture data start ######
  metrics:
    tags:
      application: ${spring.application.name}
#### Metrics related config for prometheus to capture data end ######

########## Open telemetry Start #######################
logging:
  pattern:
    level: "%5p [${spring.application.name},%X{trace_id},%X{span_id}]"
########## Open telemetry End #######################